# https://circleci.com/docs/2.0/local-cli/

defaults: &defaults
  docker:
    - image: circleci/node:9
  working_directory: ~/uxscoreboard
  environment:
    BUILD_DIR: ./dist
    NODE_APP: ./app.js

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/uxscoreboard
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}s
      - run: yarn
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn test
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths: .

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/uxscoreboard
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Fix host authenticity for $DROPLET_IP
          command: |
            ssh-keyscan $DROPLET_IP >> ~/.ssh/known_hosts
      - run:
          name: Keyscan Github (HACK)
          command: ssh-keyscan -H github.com >> ~/.ssh/known_hosts # - add_ssh_keys:
      - add_ssh_keys
      - run:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              sudo apt-get update && sudo apt-get install rsync
              rsync -avce ssh . $DROPLET_USER@$DROPLET_IP:/home/zac/apps/uxscoreboard
            elif [ "${CIRCLE_BRANCH}" = "staging" ]; then
              sudo apt-get update && sudo apt-get install rsync
              rsync -avce ssh . $DROPLET_USER@$DROPLET_IP:/home/zac/apps/uxscoreboard-staging
            else
              echo "Not master branch, dry run only"
            fi

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - staging
